RockPlayer/urls.py
from django.urls import path
from . import views


app_name = 'RockPlayer'

urlpatterns = [
    path('login', views.signin, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('signup', views.signup, name='signup'),
    path('', views.Index, name='index'),
    path('(?P<album_id>[0-9]+)/', views.Detail, name='detail'),
    path('new-album/', views.create_album, name='create-album'),
    path('<int:pk>/update-album/', views.AlbumUpdateView.as_view(), name='update-album'),
    path('(?P<album_id>[0-9]+)/delete-album', views.album_delete, name='delete-album'),
    path('(?P<album_id>[0-9]+)/new-song/', views.create_song, name='create-song'),
    path('<int:pk>/update-song/', views.SongUpdateView.as_view(), name='update-song'),
    path('(?P<album_id>[0-9]+)/delete-song/(?P<song_id>[0-9]+)/', views.delete_song , name='song-delete')

]

musicplayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RockPlayer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RockPlayer/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Album(models.Model):
    name = models.CharField(max_length=35)
    artist = models.CharField(max_length=45)
    album_genre = models.CharField(max_length=45)
    album_cover = models.FileField()
    def get_absolute_url(self):
        return reverse('RockPlayer:index')

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_name = models.CharField(max_length=25)
    song_audio = models.FileField()

    def get_absolute_url(self):
        return reverse('RockPlayer:detail')

RockPlayer/forms.py
from django import forms
from .models import Album, Song
from django.contrib.auth.models import User

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['name', 'artist', 'album_genre', 'album_cover']

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_name', 'song_audio']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

RockPlayer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Album, Song
from .forms import AlbumForm, SongForm, UserForm
from django.views.generic import UpdateView
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='RockPlayer:login')

def Index(request):
    albums = Album.objects.all()
    return render(request, 'RockPlayer/index.html', {'albums':albums})

def Detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'RockPlayer/detail.html', {'album':album})

def create_album(request):
    form = AlbumForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        albums = Album.objects.all()
        for album in albums:
            if album.name == form.cleaned_data['name']:
                context = {
                    'form':form,
                    'message': 'Album already added',
                }
                return render(request, 'RockPlayer/create-album.html', context)
        album = form.save(commit=False)
        album.album_cover = request.FILES['album_cover']
        album.save()
        return render(request, 'RockPlayer/detail.html', {'album':album})
    return render(request, 'RockPlayer/create-album.html', {'form':form})

class AlbumUpdateView(UpdateView):
    model = Album
    fields = ['name', 'artist', 'album_genre', 'album_cover']
    template_name = 'RockPlayer/create-album.html'

def album_delete(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect('/')

def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        for s in album.song_set.all():
            if s.song_name == form.cleaned_data['song_name']:
                context={
                    'form':form,
                    'message':'You already added that song',
                }
                return render(request, 'RockPlayer/create-song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.song_audio = request.FILES['song_audio']
        song.save()
        return render(request, 'RockPlayer/detail.html', {'album':album})
    return render(request, 'RockPlayer/create-song.html', {'form':form})


class SongUpdateView(UpdateView):
    model = Song
    fields = ['song_name', 'song_audio']
    template_name = 'RockPlayer/create-song.html'

def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = get_object_or_404(Song, pk=song_id)
    song.delete()
    context = {
        'album':album,
        'message': 'Song deleted successfully',
    }
    return render(request, 'RockPlayer/detail.html', {'album':album})

def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('RockPlayer:index')
    return render(request, 'registration/signup.html', {'form':form})

def signin(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('RockPlayer:index')
    return render(request, 'registration/login.html')

def logout_user(request):
    logout(request)
    context = {
        'message':'Logged out',
    }
    return render(request, 'registration/login.html', context)
    

RockPlayer/templates/RockPlayer/base.html
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>

{% load static %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'music/css/style.css' %}"/>
</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'RockPlayer:index' %}">RockPlayer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'RockPlayer:index' %}">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#"><i class="fas fa-headphones"></i> Albums</a></li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-info">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'RockPlayer:create-album' %}"><i class="fas fa-plus-square"></i> Add Album</a></li>
        <li><a href="{% url 'RockPlayer:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}
</body>
</html>

RockPlayer/templates/RockPlayer/create-album.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
{% extends 'RockPlayer/base.html' %}
{%block title%}{% if object %}Update Album{% else %}Add album{% endif %}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<body style="background-color:#001a33">
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-info panel-body">
                <h3 class="text-primary">{% if object %}Update Album{% else %}Add album{% endif %}</h3>
                <hr>
                <form method="POST" enctype="multipart/form-data">
                    {% if message %}<div class="alert alert-danger"><h4 class="text-primary">{{ message }}</h4></div>{% endif %}
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-info">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>

RockPlayer/templates/RockPlayer/create-song.html
{% extends 'RockPlayer/base.html' %}
{% load crispy_forms_tags %}
{% block title %}New Song{%endblock %}
{% block content %}
<body  style="background-color:#001a33">
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 class="text-success text-capitalize">new song</h3>
                    <hr>
                    <form method="POST" enctype="multipart/form-data">
                        {% if message %}<div class="alert alert-warning"><h4>{{ message }}</h4></div>{% endif %}
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>

RockPlayer/templates/RockPlayer/detail.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
{% extends 'RockPlayer/base.html' %}
{% block title %}{{album.name}} by {{album.artist}}{% endblock %}
{% block content %}
<body style="background-color:#001a33">
<div class="container-fluid">
    <div class="row">
        <!-- Album Info -->
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <img src="{{ album.album_cover.url }}" class="img img-responsive" alt="" style="height:250px; width:250px;">
                    <div class="caption">
                        <h4>{{ album.name }}</h4>
                        <h4>{{ album.artist }}</h4>
                    </div>
                </div>
            </div>
        </div>
        <!-- End album info -->

    <!-- Song Info -->
    <div class="col-sm-9">
    <ul class="nav nav-pills">
        <li class="active"><a href="">Songs</a></li>
        <li><a href="{% url 'RockPlayer:create-song' album.id %}">Add song</a></li>
    </ul>
    <div class="panel panel-default" style="margin:5px;">
        <div class="panel-body">
            <h3 class="text-info">Songs {% if message %} {{ message }}{% endif %}</h3>
            <hr>
            <table class="table">
                <thead>
                <th>Song Name</th>
                <th>Audio</th>
                <th>Favourite</th>
                <th>Action</th>
                </thead>
                <tbody>
                {% if album.song_set %}
                {% for song in album.song_set.all %}
                <tr>
                    <td>{{ song.song_name }}</td>
                    <td><a href="{{ song.song_audio.url }}" class="btn btn-info btn-sm" target="_blank"><i class="fas fa-play"></i></a></td>
                    <td><a href="" class="btn btn-success btn-sm"><i class="fas fa-star"></i></a></td>
                    <td><a href="{% url 'RockPlayer:update-song' song.id%}" class="btn btn-warning btn-sm"><i class="fas fa-pen"></i></a>&nbsp;
                        <a href="{% url 'RockPlayer:song-delete' album.id song.id %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>

            </table>

        </div>
    </div>
    </div>
    </div>

    <!-- End song info -->



    </div>
</div>
{% endblock %}
</body>

RockPlayer/templates/RockPlayer/index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
{% extends 'RockPlayer/base.html' %}
{% block title %}RockPlayer{% endblock %}
{% block content %}
<body style="background-color:#001a33">
<div class="container-fluid">
    <div class="row">
        {% if albums %}
        {% for album in albums %}
            <div class="col-sm-3">
                <div class="thumbnail">
                    <a href="{% url 'RockPlayer:detail' album.id %}">
                    <img src="{{ album.album_cover.url }}" class="img img-responsive img-circle" alt="" style="height:250px; width:250px;">
                    </a>
                    <div class="caption">
                        <i class="fas fa-compact-disc"></i>&nbsp;<p>{{ album.name }}</p>
                        <i class="fas fa-user-alt"></i>&nbsp;<p>{{ album.artist }}</p>
                        <a href="{% url 'RockPlayer:update-album' album.id %}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'RockPlayer:delete-album' album.id %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                        <a href="" class="btn btn-success btn-sm" style="float: right;"><i class="fas fa-heart"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}
</body>